# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  release:
   types: [ created ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    uses: ./.github/workflows/runtest.yml  # use the callable tests job to run tests
  build:
    needs: [ tests ]  # require tests to pass before deploy runs
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
         name: Android build
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload files to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release.txt
      - name: Trigger Workflow in Another Repository
        run: |
          TAG_NAME=$(curl -s "https://api.github.com/repos/saikrishna321/trigger-workflow/tags" | grep -m 1 '"name"' | sed -E 's/.*"name": "([^"]+)".*/\1/') 
          # Set the required variables
          repo_owner="saikrishna321" 
          repo_name="auto-update-readme"  
          event_type="server-update" 
          service="Server to Driver"
          version=$TAG_NAME
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
