# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [pull_request, workflow_call]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
         name: Android build
         path: |
          ${{ github.workspace }}/Release.txt
